### ISSUE TITLE
Test motion profiling

### ISSUE THREAD

**Issue by KyroVibe** [Team997Coders/2019DeepSpace#21]
Follow a customized spline.

**Comment by ethanbeez** [comment]
Would you consider this synonymous with motion profiling? @KyroVibe

**Comment by ethanbeez** [comment]
There is code from last year that was at least semi-functioning on the [PathFinder](https://github.com/Team997Coders/2019DeepSpace/tree/PathFinder) branch. This just needs to be tested before we can know where to go.

**Comment by ethanbeez** [comment]
Closing this for non-specificity. Relevant issues to motion profiling will be broken down in other issues.

**Comment by KyroVibe** [comment]
Do you not have class?
