### ISSUE TITLE
Configure sensors for front

### ISSUE THREAD

**Issue by ethanbeez** [Team997Coders/2019DeepSpace#30]
As it currently stands, our sensors for line following/distance measurements only works on one side of the robot.

**Comment by KyroVibe** [comment]
I call not it

**Comment by MrKangs** [comment]
Well I call it and I am done with it (not tested it yet)

**Comment by ethanbeez** [comment]
As of this weekend, we made the sensors used (front or back) dependent on which side the `scoringSideReversed` variable orients us to once the command is called. On top of that, it is now set up to orient the drivetrain based off whether we are following a line backwards or forwards, and undo this flipping afterwards.

**Comment by ethanbeez** [comment]
Outdated issue! Begone!
